"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useSession } from "@/lib/session-context";
import { getCheatSheet } from "@/lib/api";
import { FileDown, Printer, RefreshCw } from "lucide-react";
import ReactMarkdown from "react-markdown";

export default function CheatSheetsPage() {
  const { courseId } = useSession();
  const [loading, setLoading] = useState(true);
  const [cheatSheet, setCheatSheet] = useState<any>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    loadCheatSheet();
  }, [courseId]);

  async function loadCheatSheet() {
    try {
      setLoading(true);
      setError("");
      const data = await getCheatSheet(courseId);
      setCheatSheet(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  function handlePrint() {
    window.print();
  }

  function handleDownload() {
    if (!cheatSheet) return;

    const element = document.createElement("a");
    const file = new Blob([cheatSheet.content], { type: "text/markdown" });
    element.href = URL.createObjectURL(file);
    element.download = `${cheatSheet.course_name}-cheat-sheet.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600 dark:text-gray-400">Generating cheat sheet...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-4xl mx-auto">
        <Card>
          <CardContent className="pt-6">
            <div className="text-center space-y-4">
              <p className="text-red-600 dark:text-red-400">{error}</p>
              <Button onClick={loadCheatSheet}>
                <RefreshCw className="mr-2 h-4 w-4" />
                Try Again
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header with Actions */}
      <div className="flex items-center justify-between print:hidden">
        <div>
          <h1 className="text-2xl font-bold">Cheat Sheet</h1>
          <p className="text-gray-600 dark:text-gray-400 mt-1">
            Quick reference for {cheatSheet?.course_name || "your course"}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={() => loadCheatSheet()}>
            <RefreshCw className="mr-2 h-4 w-4" />
            Regenerate
          </Button>
          <Button variant="outline" onClick={handlePrint}>
            <Printer className="mr-2 h-4 w-4" />
            Print
          </Button>
          <Button onClick={handleDownload}>
            <FileDown className="mr-2 h-4 w-4" />
            Download
          </Button>
        </div>
      </div>

      {/* Cheat Sheet Content */}
      <Card className="print:shadow-none print:border-0">
        <CardHeader className="print:pb-2">
          <CardTitle className="text-center">
            {cheatSheet?.course_name || "Course"} - Quick Reference Cheat Sheet
          </CardTitle>
          <p className="text-sm text-center text-gray-600 dark:text-gray-400 print:text-gray-800">
            Covering {cheatSheet?.concepts_covered || 0} key concepts
          </p>
        </CardHeader>
        <CardContent>
          <div className="prose dark:prose-invert max-w-none prose-headings:text-blue-600 dark:prose-headings:text-blue-400 prose-strong:text-gray-900 dark:prose-strong:text-gray-100 print:prose-headings:text-black print:prose-p:text-black print:prose-li:text-black print:prose-strong:text-black">
            {cheatSheet?.content ? (
              <ReactMarkdown>{cheatSheet.content}</ReactMarkdown>
            ) : (
              <p className="text-gray-600">No content available</p>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Print-specific footer */}
      <div className="hidden print:block text-center text-sm text-gray-600 mt-8">
        <p>Generated by KOP AI • {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
}
